### ISSUE TITLE
Auto-focus in the editor on page load

### ISSUE THREAD

**Issue by lylo** [KonnorRogers/rhino-editor#169]
What is the correct way to have the editor receive focus on page load, if this is indeed possible? I have a Stimulus controller which calls `focus()` on my `<rhino-editor>` element but this doesn't seem to work (no error, just returns `undefined`). I've also tried adding `autofocus` in the HTML.

**Comment by KonnorRogers** [comment]
@lylo there's a `editorOptions` hook on the element itself, but I don't particularly love the API which supports "autofocus". https://github.com/KonnorRogers/rhino-editor/blob/a3db210c2b1300d15017bc6c4fd69600deb043ed/src/exports/elements/tip-tap-editor-base.ts#L259

However, it requires extending the class since its a function and not a property. I think I may do something similar to the Extensions API where its just `this.editorOptions = {}` and then you can extend it.

For right now, I think this would be the best way:

```js
document.addEventListener("rhino-initialize", async (e) => {
  const rhinoEditor = e.target
   
  await rhinoEditor.updateComplete
  rhinoEditor.querySelector(".ProseMirror").focus()
})
```

With a stimulus controller, I'd probably do something like this:

```html
<rhino-editor data-controller="rhino" data-action="rhino-initialize#rhino->focus"></rhino-editor>
```


```js
class extends Controller {
  focus () { 
     const rhinoEditor = this.element
     await rhinoEditor.updateComplete
     rhinoEditor.editorElement.focus()
  }
}
```

**Comment by lylo** [comment]
That's really neat, thanks for explaining @KonnorRogers, works a treat 👌
